apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busy
  name: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox:1.28
        name: busybox
        env:
        - name: STAGE
          value: K8S
        - name: NodeIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: busy
              key: PASSWORD
        envFrom:
        - configMapRef:
            name: busy
      
