apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: hello-www
spec:
  ingressClassName: nginx
  rules:
  - host: hello.stage.local
    http:
      paths:
      - backend:
          service:
            name: hello
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: www.stage.local
    http:
      paths:
      - backend:
          service:
            name: www
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
