apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: all-labo
  namespace: labo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: all-labo
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob
