apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

resources:
- ../base

namespace: dev

images:
- name: bob2606/hello-http
  newtag: latest

replicas:
  - name: hello
    count: 2

configMapGenerator:
  - name: hello
    envs:
    - hello.env

replacements:
- source:
    kind: ConfigMap
    name: hello
    fieldPath: data.PORT
  targets:
  - select: 
      kind: Deployment
      name: hello
      namespace: dev
    fieldPaths:
      - spec.template.spec.containers.0.ports.0.containerPort
- source:
    kind: ConfigMap
    name: hello
    fieldPath: data.INGRESS_PATH
  targets:
  - select:
      kind: Ingress
      name: hello
      namespace: dev
    fieldPaths:
      - spec.rules.0.http.paths.0.path
